export const FOOTER_LIST = [
  { id: 1, text: '소개' },
  { id: 2, text: ' · ' },
  { id: 3, text: '도움말' },
  { id: 4, text: ' · ' },
  { id: 5, text: '홍보 센터' },
  { id: 6, text: ' · ' },
  { id: 7, text: 'API' },
  { id: 8, text: ' · ' },
  { id: 9, text: '채용 정보' },
  { id: 10, text: ' · ' },
  { id: 11, text: '개인정보처리방침' },
  { id: 12, text: ' · ' },
  { id: 13, text: '약관' },
  { id: 14, text: ' · ' },
  { id: 15, text: '위치' },
  { id: 16, text: ' · ' },
  { id: 17, text: '언어' },
];
